# Generated by Django 5.2.4 on 2025-10-23 06:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetotp',
            name='last_sent_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 10, 23, 6, 21, 21, 138258, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
